# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2a7761470954ee115200ce9297195d03bb8dc0e060ed43360cb6c5fbb929b5b020b025ab01768453a1584947aebf67c92386f7178823a5694ab20075a8d75c2

test:
  secret_key_base: 23ce19261bd8b7123d560184f84eb1f94b65057e8558a28c49f1963d1d544956992f1fbbb7d5764ed40081d5376e28daf9deacbb9734e941ba4bb75c5c4426f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
